Int 916 initial release
polarityio/alphamountain pull request #1
Opened 2023-03-29 19:54 UTC by CJ-Polarity

2023-04-13 17:43 UTC, CJ-Polarity commented on components/block.js
> +  _getThreatColor(score) {
Removed `_getThreatColor(score)`

2023-04-13 17:45 UTC, CJ-Polarity commented on components/block.js
> +        console.log('quota', quota);
Removed log

2023-04-13 17:46 UTC, CJ-Polarity commented on components/block.js
>          outerThis.set(
Removed unneeded `const outerThis = this;`

2023-04-13 17:47 UTC, CJ-Polarity commented on components/block.js
>            outerThis.set('gettingQuotaErrorMessage', '');
Resolved

2023-04-13 18:54 UTC, CJ-Polarity commented on components/block.js
>          setTimeout(() => {
Fixed

2023-04-16 00:43 UTC, sarus requested changes
@CJ-Polarity Looks like you might need to sync up the `config.json` for the integration checklist to pass.  I use this little bash script to do the syncing:
```
#!/bin/bash

integration=$1;

node -e "console.info(JSON.stringify(require('./$integration/config/config.js'), null, 2))" > "./$1/config/config.json"
```

Save it to a script like `sync-configs.sh` and make it executable.  For ease of use I just put in in my integrations folder.  Then you can run it like this:

```
./sync-configs.sh alphaMountain
```

and it will create a config.json that matches the config.js in the specified integration directory.

2023-04-16 00:46 UTC, sarus commented
@CJ-Polarity Also noticed that the package.json is specifying an older postman.  Can you update to the latest and regenerate the package-lock:

```
"postman-request": "^2.88.1-postman.32" //<=== .32 instead of .31
```

2023-04-16 01:36 UTC, sarus requested changes
Some additional comments.  We'll also need to do some template and CSS cleanup but I didn't put specific comments in this for that (probably best to just do a pair programming session)

Finally, the code you based this integration off of has some logic to strip sensitive data (api keys), but that code assumes the api key is on the header whereas in the alphaMountain api it is on the body).  If you want that code to work we'll need to update.

Ideally we would be able to provide slightly more intuitive error messages to users (e.g., differentiate between a 401 auth error and a 429 license key limit error).

2023-04-16 01:36 UTC, sarus commented on components/block.js
> +          if (this.get('isDestroyed')) {
@CJ-Polarity This needs to be:

```
if (!this.get('isDestroyed')){
```

Right now it will only trigger if the component is destroyed which is the opposite of what we want.

2023-04-16 01:36 UTC, sarus commented on components/block.js
> +    this.set(this.isRunningKeyMap[endpoint], true);
Still seeing this error here:

```
neon-tetra.js:1412 Error: Assertion Failed: The key provided to set must be a string or number, you passed true
    at assert (vendor.js:52499)
    at set (vendor.js:31416)
    at Class.set (vendor.js:44290)
    at Class.getApiEndpointQuota (eval at _evalConfigJS (neon-tetra.js:75295), <anonymous>:49:10)
    at Class.getApiEndpointQuota (eval at _evalConfigJS (neon-tetra.js:75295), <anonymous>:41:12)
    at Class.send (vendor.js:47965)
    at Class.superWrapper [as send] (vendor.js:47233)
    at vendor.js:26551
    at instrument (vendor.js:53930)
    at vendor.js:26550
    at Backburner._run (vendor.js:70306)
    at Backburner._join (vendor.js:70290)
    at Backburner.join (vendor.js:70061)
    at join (vendor.js:57484)
    at ActionState.handler (vendor.js:26525)
    at HTMLButtonElement.<anonymous> (vendor.js:49366)
    at HTMLBodyElement.dispatch (vendor.js:10286)
    at HTMLBodyElement.elemData.handle (vendor.js:10090)
```

The first parameter into `this.set` should be the key in string form.

2023-04-16 01:36 UTC, sarus commented on components/block.js
> +    let reputation = this.get('details.threatScore.score');
This reputation variable is unused

2023-04-16 01:36 UTC, sarus commented on src/queries/getImpersonate.js
> +    filter(get('isURL')),
The filter here is not strictly necessary as the integration is configured to only receive URLs (via the config.js).

2023-04-16 01:36 UTC, sarus commented on src/queries/getCategories.js
> +  const urlEntities = filter((entity) => entity.isURL, entities);
Not strictly necessary as all entities will always be URLs since the integration config specifies only URLs as a valid `entityType`

2023-04-17 15:03 UTC, CJ-Polarity commented on src/queries/getCategories.js
> +  const urlEntities = filter((entity) => entity.isURL, entities);
Removed filter function from `getCategories.js` for keeping only urls

2023-04-17 15:23 UTC, CJ-Polarity commented on components/block.js
> +          if (this.get('isDestroyed')) {
Changed

2023-04-19 13:37 UTC, CJ-Polarity commented on components/block.js
> +    this.set(this.isRunningKeyMap[endpoint], true);
`this.isRunningKeyMap[endpoint]` had the wrong variable name stored and was causing the error

2023-04-19 19:06 UTC, merged